# This is a basic workflow to help you get started with Actions

name: CI

env:
  CHAT_ID: "-957274343"
  BOT_TOKEN: "1568895430:AAG22Vr73NTS_U40qzy0B_jiJVmUj6mf1Qk"
  MESSAGE: "Github CI/CD message"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Send telegram notification
        run: |
          echo $CHAT_ID
          echo $MESSAGE
          chmod +x ./utility/send_notify.sh
          CHAT_ID=$CHAT_ID BOT_TOKEN=$BOT_TOKEN MESSAGE=$MESSAGE ./utility/send_notify.sh